### ISSUE TITLE
Get tron address and private key from 12 seed phrase

### ISSUE THREAD

**Issue by Imdavyking** [xclud/dart_wallet#2]
how can i get tron address and private key from 12 seed, if also how to get balance and send token

**Comment by xclud** [comment]
```
import 'package:wallet/wallet.dart' as wallet;

final mnemonic = '<YOUR MNEMONIC>';
final passphrase = '';

final seed = wallet.mnemonicToSeed(mnemonic, passphrase: passphrase);
final master = wallet.ExtendedPrivateKey.master(seed, wallet.xprv);
final root = master.forPath("m/44'/195'/0'/0/0");

final privateKey =
    wallet.PrivateKey((root as wallet.ExtendedPrivateKey).key);
final publicKey = wallet.tron.createPublicKey(privateKey);
final address = wallet.tron.createAddress(publicKey);

print(address);
```

**Comment by Imdavyking** [comment]
thank you so much...please what of balance and send a payment

**Comment by xclud** [comment]
The package is in the very early state and does not support these functionalities (thou it supports signing messages and verifying for Tron).

Please take a look at this package https://pub.dev/packages/tron and this issue https://github.com/xclud/dart_tron/issues/1. It might help.

Closing this issue, but please feel free to open a new issue any time.

**Comment by Imdavyking** [comment]
Please just the validation of tron address

**Comment by xclud** [comment]
Use `Base58CheckCodec.bitcoin()` and try decoding the address string. If it does not throw an exception and the `version` filed is `0x41`, the Tron address is valid.

**Comment by Imdavyking** [comment]
Thank you so much
