### ISSUE TITLE
How to Create a TRX Transaction using the package?

### ISSUE THREAD

**Issue by ArunBabu98** [xclud/dart_wallet#20]
Can you provide an example for creating trx transaction using the library?

**Comment by Imdavyking** [comment]
Hi ,xclud please this

**Comment by ArunBabu98** [comment]
> Hi ,xclud please this

I found this package instead that includes TRX,

https://github.com/mrtnetwork/on_chain

**Comment by Imdavyking** [comment]
Thank you
